manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: alabahuy & rizalfr
      url-base: https://github.com/alabahuy
  projects:
    - name: zmk
      remote: rizalfr
      revision: main
      import: app/west.yml
  self:
    path: config
